const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const outputPath = path.join(__dirname, '..', 'Amcal_Woy_Woy_Staff_User_Guide.pdf');
const doc = new PDFDocument({
  size: 'A4',
  margin: 40,
  bufferPages: true,
  info: {
    Title: 'Amcal Pharmacy Woy Woy - Staff Operating Manual',
    Author: 'Amcal Woy Woy Management',
    Subject: 'Amcal Woy Woy Roster - Employee User Guide & Operations Manual',
    Keywords: 'Amcal, Pharmacy, Roster, Staff Guide, Pharmacy Award 2026, Time Clock'
  }
});

const stream = fs.createWriteStream(outputPath);
doc.pipe(stream);

// --- Theme Colors ---
const PRIMARY = '#0f172a';    // Dark Navy
const ACCENT = '#0284c7';     // Cyan Blue
const SUCCESS = '#059669';    // Emerald Green
const WARNING = '#d97706';    // Amber
const TEXT_DARK = '#1e293b';  // Slate Dark
const TEXT_MUTED = '#64748b'; // Slate Muted
const BG_LIGHT = '#f8fafc';   // Light Gray Box
const BORDER = '#e2e8f0';

function drawHeader(title) {
  doc.rect(40, 40, 515, 50).fill(PRIMARY);
  
  // Amcal Brand Mark
  doc.fillColor('#ffffff').fontSize(18).font('Helvetica-Bold').text('Amcal+', 55, 52);
  doc.fillColor(ACCENT).fontSize(10).font('Helvetica-Bold').text('WOY WOY ROSTER', 130, 58);
  
  doc.fillColor('#ffffff').fontSize(11).font('Helvetica-Bold').text(title.toUpperCase(), 320, 56, { align: 'right', width: 220 });
}

function drawSectionHeading(num, title) {
  doc.moveDown(0.8);
  const y = doc.y;
  doc.rect(40, y, 515, 24).fill(BG_LIGHT);
  doc.rect(40, y, 4, 24).fill(ACCENT);
  doc.fillColor(TEXT_DARK).fontSize(12).font('Helvetica-Bold').text(`${num}. ${title}`, 52, y + 6);
  doc.moveDown(0.6);
}

function drawSubHeading(title) {
  doc.moveDown(0.4);
  doc.fillColor(ACCENT).fontSize(10).font('Helvetica-Bold').text(title);
  doc.moveDown(0.2);
}

function drawParagraph(text) {
  doc.fillColor(TEXT_DARK).fontSize(9.5).font('Helvetica').text(text, { lineGap: 3 });
  doc.moveDown(0.3);
}

function drawBullet(title, text) {
  const y = doc.y;
  doc.fillColor(ACCENT).fontSize(10).text('•', 48, y);
  doc.fillColor(TEXT_DARK).fontSize(9.5).font('Helvetica-Bold').text(`${title}: `, 60, y, { continued: true });
  doc.font('Helvetica').text(text, { lineGap: 2 });
  doc.moveDown(0.25);
}

function drawInfoBox(title, lines, color = ACCENT) {
  doc.moveDown(0.4);
  const startY = doc.y;
  const boxHeight = (lines.length * 14) + 24;
  
  doc.rect(40, startY, 515, boxHeight).fill('#f0f9ff').stroke(BORDER);
  doc.rect(40, startY, 4, boxHeight).fill(color);
  
  doc.fillColor(color).fontSize(9.5).font('Helvetica-Bold').text(`[NOTE] ${title}`, 52, startY + 8);
  
  let currY = startY + 22;
  lines.forEach(line => {
    doc.fillColor(TEXT_DARK).fontSize(8.8).font('Helvetica').text(line, 52, currY);
    currY += 13;
  });
  
  doc.y = startY + boxHeight + 6;
}

// ==========================================
// PAGE 1: COVER & SYSTEM ACCESS
// ==========================================
drawHeader('Staff Operating Manual');

doc.moveDown(2);
doc.fillColor(PRIMARY).fontSize(20).font('Helvetica-Bold').text('Amcal Pharmacy Woy Woy');
doc.fillColor(ACCENT).fontSize(14).font('Helvetica-Bold').text('Staff Roster & Time Clock System Operations Guide (v9.2.8)');
doc.fillColor(TEXT_MUTED).fontSize(9).font('Helvetica').text('Published: August 2026 | System Edition v9.2.8 | Canonical App: https://woywoyamcalroster.vercel.app');

doc.moveDown(1);

drawSectionHeading('1', 'System Overview & App Access');
drawParagraph('Amcal Woy Woy Roster is the official employee roster, time clocking, and shift management platform for Amcal Pharmacy Woy Woy. This platform allows team members to view weekly schedules, clock in/out with GPS geofencing, manage Fair Work break entitlements, swap shifts with colleagues, and request time off.');

drawSubHeading('1.1 Web Access & PWA Mobile Installation');
drawBullet('Canonical Web Address', 'Access the system from any browser at https://woywoyamcalroster.vercel.app');
drawBullet('iPhone (iOS) Installation', 'Open Safari -> tap the Share icon -> select "Add to Home Screen".');
drawBullet('Android Installation', 'Open Chrome -> tap the three dots menu -> select "Install App" or "Add to Home Screen".');

drawSubHeading('1.2 Employee Account Registration & Login');
drawBullet('Invitation Link', 'New staff members will receive an official invitation link (?invite=CODE) generated by the Manager. Click the link to set your password and register.');
drawBullet('Standard Login', 'Enter your registered email address and password on the home login screen.');
drawBullet('Password Recovery', 'Click "Forgot Password?" to receive a direct Supabase password reset link in your email inbox.');

drawInfoBox('Mobile Offline Capability (PWA)', [
  'Amcal Woy Woy Roster includes Progressive Web App (PWA) offline support.',
  'If mobile network drops temporarily, your timecard stamps will queue locally and auto-sync once reconnected.'
], SUCCESS);

drawSectionHeading('2', 'Dashboard & My Weekly Summary');
drawParagraph('Upon logging in, staff members arrive at their personalized Employee Dashboard.');
drawBullet('My Weekly Summary', 'Displays your total scheduled hours for the current week and your estimated gross earnings.');
drawBullet('My Timeclock Status', 'Live indicator showing your current status: Not Clocked In, Working (Clocked In), or On Break.');
drawBullet('My Next Shift', 'Shows your next upcoming scheduled shift date, start/end time, and assigned roster role.');
drawBullet('Quick Actions', 'Direct 1-tap buttons to open the Clock Terminal, request time off, or view full schedules.');

// ==========================================
// PAGE 2: SCHEDULER, DAILY VIEW & BREAKS
// ==========================================
doc.addPage();
drawHeader('Schedules & Break Entitlements');

drawSectionHeading('3', 'Viewing Schedules (Weekly & Daily Views)');
drawParagraph('Staff members can review store rosters using two complementary view modes:');

drawSubHeading('3.1 Weekly Scheduler Grid');
drawBullet('7-Day Grid View', 'Displays all staff shifts for Monday through Sunday. Navigate between weeks using the left/right arrow buttons.');
drawBullet('Role Color Badges', 'Shifts are color-coded by position (e.g. Pharmacist Manager, Dispensary Tech, Pharmacy Assistant, Webster).');
drawBullet('Shift Break Badges', 'Every shift displaying 4+ hours shows break icons (e.g. [Lunch: 30m] | [Rest: 2x 10m Paid]).');

drawSubHeading('3.2 Daily View & Interactive Timeline');
drawBullet('Daily Timeline Bar', 'Visual graph showing coverage across store trading hours (8:30 AM - 5:30 PM). Hover/tap any bar for shift details.');
drawBullet('Daily Shifts Table', 'Lists all rostered staff for the selected day along with assigned roles, shift times, break entitlements, and manager notes.');
drawBullet('A4 Roster Print', 'Click "Print Roster" to generate an A4 landscape formatted printout suitable for the dispensary notice board.');

drawSectionHeading('4', 'Pharmacy Industry Award 2026 Break Entitlements');
drawParagraph('Amcal Woy Woy Roster strictly enforces break rules under the latest Pharmacy Industry Award 2026 [MA000084] (Clause 16).');

// Break Table
const tableY = doc.y + 5;
doc.rect(40, tableY, 515, 90).stroke(BORDER);
doc.rect(40, tableY, 515, 20).fill(PRIMARY);

doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold');
doc.text('Shift Duration (Hours Worked)', 50, tableY + 5);
doc.text('Unpaid Meal Break (Lunch)', 240, tableY + 5);
doc.text('Paid Rest Break (10 Min)', 400, tableY + 5);

const rows = [
  ['Less than 4 Hours', 'No Break Required', 'No Break Required'],
  ['4.0 Hours to < 5.0 Hours', 'No Break Required', '1 x 10-Minute Paid Rest'],
  ['5.0 Hours to < 7.6 Hours', '1 x 30-Minute Unpaid Lunch', '1 x 10-Minute Paid Rest'],
  ['7.6 Hours or More (Full Shift)', '1 x 30-Minute Unpaid Lunch', '2 x 10-Min Paid Rest (Morning & Afternoon)']
];

let rY = tableY + 22;
rows.forEach((r, idx) => {
  if (idx % 2 === 1) doc.rect(40, rY - 2, 515, 17).fill('#f8fafc');
  doc.fillColor(TEXT_DARK).fontSize(8.5).font('Helvetica');
  doc.text(r[0], 50, rY);
  doc.text(r[1], 240, rY);
  doc.text(r[2], 400, rY);
  rY += 17;
});

doc.y = tableY + 102;

drawInfoBox('Important Note on Paid Rest Breaks', [
  '• 10-minute Rest Breaks are PAID by law and are NEVER deducted from your timecard hours.',
  '• Only the 30-minute Lunch Break is unpaid and deducted from gross shift hours.'
], WARNING);

// ==========================================
// PAGE 3: TIME CLOCK, SWAPS, LEAVE & UPDATES
// ==========================================
doc.addPage();
drawHeader('Time Clock & Requests');

drawSectionHeading('5', 'Time Clock Terminal & Geofencing');
drawParagraph('Staff members clock in and out using the digital Time Clock Terminal.');
drawBullet('Geofencing Protection', 'To ensure compliance, clocking in requires location access and must be within ~500m of Amcal Pharmacy Woy Woy (-33.4842, 151.3259).');
drawBullet('Clocking In', 'Select your name from the dropdown and click "Clock In".');
drawBullet('Starting 30m Lunch Break', 'Click "30m Lunch (Unpaid)" when taking your unpaid meal break.');
drawBullet('Starting 10m Paid Rest Break', 'Click "10m Rest (Paid)" when taking your 10-minute tea/rest break.');
drawBullet('Ending Break', 'Click "End Break" to resume active duty status.');
drawBullet('Clocking Out', 'Click "Clock Out" at the end of your shift.');

drawSectionHeading('6', 'Shift Swaps & Peer Cover Requests');
drawParagraph('If you are unable to work a scheduled shift, you can initiate a shift swap:');
drawBullet('Submitting a Swap Request', 'Open the Shift Swap Board -> click "Request Shift Swap" -> select your shift and the target staff member.');
drawBullet('Peer Notification', 'The selected colleague will see the cover request on their scheduler badge.');
drawBullet('Manager Approval', 'Once the colleague agrees, the Manager approves the swap, automatically updating the roster.');

drawSectionHeading('7', 'Requesting Time Off / Leave');
drawParagraph('Submit leave requests directly in the app for Manager review.');
drawBullet('Types of Leave', 'Select Annual Leave, Sick Leave, Carer\'s Leave, or Unpaid Leave.');
drawBullet('Dates & Reason', 'Specify start date, end date, and any relevant notes (e.g. medical certificate attached).');
drawBullet('Approval Status', 'Track real-time status (Pending, Approved, Rejected) under the Time Off tab.');

drawSectionHeading('8', 'System Updates & Technical Support');
drawBullet('English Update Log (Release Notes)', 'Click the "Updates (v9.2.9)" button in the top navigation bar to review recent system improvements, live pay calculations, and Fair Work 2026 features.');
drawBullet('Technical Support', 'For assistance with logins or rosters, contact the Pharmacist Manager or system administrator.');

// --- Footer for all pages ---
const totalPages = doc.bufferedPageRange().count;
for (let i = 0; i < totalPages; i++) {
  doc.switchToPage(i);
  doc.rect(40, 780, 515, 20).fill(PRIMARY);
  doc.fillColor('#ffffff').fontSize(8).font('Helvetica')
     .text('Amcal Pharmacy Woy Woy - Confidential Roster Operations Manual', 50, 786, { lineBreak: false });
  doc.text(`Page ${i + 1} of ${totalPages}`, 450, 786, { align: 'right', width: 95, lineBreak: false });
}

doc.end();

stream.on('finish', () => {
  console.log(`✅ PDF User Guide generated successfully at: ${outputPath}`);
  
  // Auto-generate Serverless Guide Download API Endpoint
  const guideApiDir = path.join(__dirname, '..', 'api', 'schedule', 'guide');
  if (!fs.existsSync(guideApiDir)) fs.mkdirSync(guideApiDir, { recursive: true });
  
  const guideApiContent = `import type { VercelRequest, VercelResponse } from '@vercel/node';
import fs from 'fs';
import path from 'path';

export default function handler(req: VercelRequest, res: VercelResponse) {
  const origin = (req.headers.origin as string) || '';
  const allowedOrigins = [
    'https://woywoyamcalroster.vercel.app',
    'http://localhost:3000',
    'http://localhost:3002',
    'http://127.0.0.1:3000',
    'http://localhost:5173'
  ];
  if (allowedOrigins.includes(origin) || origin.endsWith('.vercel.app')) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  } else {
    res.setHeader('Access-Control-Allow-Origin', 'https://woywoyamcalroster.vercel.app');
  }
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  try {
    const pdfPath = path.join(process.cwd(), 'Amcal_Woy_Woy_Staff_User_Guide.pdf');
    if (!fs.existsSync(pdfPath)) {
      return res.status(404).json({ error: 'Staff User Guide PDF not found on server.' });
    }

    const fileBuffer = fs.readFileSync(pdfPath);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="Amcal_Woy_Woy_Staff_User_Guide.pdf"');
    res.setHeader('Content-Length', fileBuffer.length);
    res.setHeader('Cache-Control', 'public, max-age=3600');
    return res.status(200).send(fileBuffer);
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    console.error('[GuideAPI] Error:', msg);
    return res.status(500).json({ error: msg });
  }
}
`;
  fs.writeFileSync(path.join(guideApiDir, 'index.ts'), guideApiContent, 'utf8');
  console.log(`✅ Guide API endpoint generated at: ${path.join(guideApiDir, 'index.ts')}`);
});
